---

name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test templates
    strategy:
      matrix:
        template:
          - github
    uses: danieljtrowbridge/stack-templates/.github/workflows/test.yaml@main
    with:
      template: ${{ matrix.template }}
