---

name: Test

on:
  workflow_call:
    inputs:
      template:
        required: true
        type: string

jobs:
  build:
    env:
      STACK_ROOT: ${{ github.workspace }}/.stack-root
    name: Create test package
    runs-on: ubuntu-latest
    steps:
      - name: Set up Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          ghc-version: 9.4.8
          stack-setup-ghc: true
      - name: Create package using ${{ inputs.template }} template
        run: |
          stack new test-package danieljtrowbridge/${{ inputs.template }} \
            -p "author-email:danieljtrowbridge@pm.me" \
            -p "author-name:Daniel Trowbridge" \
            -p "ghc-version:9.4.8" \
            -p "github-username:danieljtrowbridge" \
            -p "resolver:lts-21.25"
          cd test-package/
          source init.sh
          ls -Ral
      - name: Upload test package artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.template }}-test-package
          path: test-package/
  lint:
    container:
      credentials:
        password: ${{ secrets.github_token }}
        username: ${{ github.actor }}
      image: ghcr.io/danieljtrowbridge/docker-fourmolu:latest
    name: Lint test package
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download test package artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.template }}-test-package
      - name: Check code formatting
        run: fourmolu --mode check test-package/
  test:
    env:
      STACK_ROOT: ${{ github.workspace }}/.stack-root
    name: Run test suite
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          ghc-version: 9.4.8
          stack-setup-ghc: true
      - name: Download test package artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.template }}-test-package
      - name: Run test suite
        run: |
          cd test-package/
          stack test test-package
