---

name: Test

on:
  workflow_call:
    inputs:
      template:
        required: true
        type: string

jobs:
  build:
    env:
      STACK_ROOT: ${{ github.workspace }}/.stack-root
    name: Create test package
    runs-on: ubuntu-latest
    steps:
      - name: Download Stack executable artifact
        uses: actions/download-artifact@v3
        with:
          name: stack-exe
      - name: Restore Stack root directory
        uses: actions/cache@v3
        with:
          key: stack-root
          path: .stack-root/
      - name: Create package using ${{ inputs.template }} template
        run: |
          chmod +x ./stack
          ./stack new test-package danieljtrowbridge/${{ inputs.template }} \
            -p "author-email:danieljtrowbridge@pm.me" \
            -p "author-name:Daniel Trowbridge" \
            -p "ghc-version:9.4.7" \
            -p "github-username:danieljtrowbridge"
          cd test-package/
          source init.sh
          ls -Ral
      - name: Upload test package artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.template }}-test-package
          path: test-package/
  lint:
    container:
      credentials:
        password: ${{ secrets.github_token }}
        username: ${{ github.actor }}
      image: ghcr.io/danieljtrowbridge/docker-fourmolu:latest
    name: Lint test package
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download test package artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.template }}-test-package
      - name: Check code formatting
        run: fourmolu --mode check test-package/
        working-directory: test-package/
  test:
    env:
      STACK_ROOT: ${{ github.workspace }}/.stack-root
    name: Run test suite
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download Stack executable artifact
        uses: actions/download-artifact@v3
        with:
          name: stack-exe
      - name: Restore Stack root directory
        uses: actions/cache/restore@v3
        with:
          key: stack-root
          path: .stack-root/
      - name: Download test package artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.template }}-test-package
      - name: Run test suite
        run: |
          chmod +x ./stack
          cd test-package/
          ../stack test test-package
